### ISSUE TITLE
build-time use of sed not working on cross

### ISSUE THREAD

**Issue by abathur** [abathur/resholve#115]
> I tried this patch to get lesspipe cross-compiling again, but there is still some issue in the bowels of resholve.
> 
> It gives a useless error message (see below), probably due to oil's cursed Python setup. After adding some debug prints I found that the real issue is that resholve is attempting to execute `/nix/store/b93plx4fg4q59dy984xhf9083xkjwxn3-gnused-armv7l-unknown-linux-gnueabihf-4.9/bin/sed` on the build platform for some reason.
> 
> <details>
>   <summary>lesspipe error</summary>
> 
> ```
> [resholve context] : invoking resholve with PWD=/nix/store/xyn66gjkjjb4364qlcipsvm018f4q0l2-lesspipe-armv7l-unknown-linux-gnueabihf-2.11
> [resholve context] RESHOLVE_LORE=/nix/store/dx6b3mr3fb9fxb9iagcg0dj9p7vr1wfi-more-binlore
> [resholve context] RESHOLVE_EXECER=cannot:/nix/store/si1v1sriszpdz7lzf2v0y1kxpvnrfw3n-glibc-armv7l-unknown-linux-gnueabihf-2.38-44-bin/bin/iconv
> [resholve context] RESHOLVE_FAKE='builtin:'\''setopt'\'' external:'\''cpio'\'';'\''isoinfo'\'';'\''cabextract'\'';'\''bsdtar'\'';'\''rpm2cpio'\'';'\''bsdtar'\'';'\''unzip'\'';'\''ar'\'';'\''unrar'\'';'\''rar'\'';'\''7zr'\'';'\''7za'\'';'\''isoinfo'\'';'\''gzip'\'';'\''bzip2'\'';'\''lzip'\'';'\''lzma'\'';'\''xz'\'';'\''brotli'\'';'\''compress'\'';'\''zstd'\'';'\''lz4'\'';'\''archive_color'\'';'\''bat'\'';'\''batcat'\'';'\''pygmentize'\'';'\''source-highlight'\'';'\''vimcolor'\'';'\''code2color'\'';'\''w3m'\'';'\''lynx'\'';'\''elinks'\'';'\''html2text'\'';'\''dtc'\'';'\''pdftotext'\'';'\''pdftohtml'\'';'\''pdfinfo'\'';'\''ps2ascii'\'';'\''procyon'\'';'\''ccze'\'';'\''mdcat'\'';'\''pandoc'\'';'\''docx2txt'\'';'\''libreoffice'\'';'\''pptx2md'\'';'\''mdcat'\'';'\''xlscat'\'';'\''odt2txt'\'';'\''wvText'\'';'\''antiword'\'';'\''catdoc'\'';'\''broken_catppt'\'';'\''sxw2txt'\'';'\''groff'\'';'\''mandoc'\'';'\''unrtf'\'';'\''dvi2tty'\'';'\''pod2text'\'';'\''perldoc'\'';'\''h5dump'\'';'\''ncdump'\'';'\''matdump'\'';'\''djvutxt'\'';'\''openssl'\'';'\''gpg'\'';'\''plistutil'\'';'\''plutil'\'';'\''id3v2'\'';'\''csvlook'\'';'\''jq'\'';'\''zlib-flate'\'';'\''lessfilter'\'''
> [resholve context] RESHOLVE_INPUTS=/nix/store/wcrl0irr3an87fbwzsg9mpj5mnfpvbk6-coreutils-armv7l-unknown-linux-gnueabihf-9.4/bin:/nix/store/xkcz43jrwq04maydv76j4cr2001r2f0s-file-armv7l-unknown-linux-gnueabihf-5.45/bin:/nix/store/pqmgk2jg8bwykqiiknmzj938scm241m5-gnugrep-armv7l-unknown-linux-gnueabihf-3.11/bin:/nix/store/b93plx4fg4q59dy984xhf9083xkjwxn3-gnused-armv7l-unknown-linux-gnueabihf-4.9/bin:/nix/store/mslz3hmikmqf41qidnnhrl3qk56jsd0f-gnutar-armv7l-unknown-linux-gnueabihf-1.35/bin:/nix/store/si1v1sriszpdz7lzf2v0y1kxpvnrfw3n-glibc-armv7l-unknown-linux-gnueabihf-2.38-44-bin/bin:/nix/store/xzbrkn3xwh0lanal0kh45bp8jp0g116q-procps-armv7l-unknown-linux-gnueabihf-3.3.17/bin:/nix/store/ahbdf9yprwi62g3rcjcb7sl7l6lz7xvf-ncurses-armv7l-unknown-linux-gnueabihf-6.4/bin
> [resholve context] RESHOLVE_INTERPRETER=/nix/store/vhrjarnl5m4mf7z52mywiqq9vrxcaqjs-bash-armv7l-unknown-linux-gnueabihf-5.2p26/bin/bash
> [resholve context] RESHOLVE_KEEP='$prog $c1 $c2 $c3 $c4 $c5 $cmd $colorizer $HOME'
> [resholve context] /nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/resholve --overwrite bin/lesspipe.sh
> ...
> Traceback (most recent call last):
>   File "/nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/.resholve-wrapped", line 4748, in <module>
>     sys.exit(punshow())
>   File "/nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/.resholve-wrapped", line 947, in punshow
>     resolve_cmdlikes()
>   File "/nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/.resholve-wrapped", line 3119, in resolve_cmdlikes
>     cmdlike.resolve()
>   File "/nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/.resholve-wrapped", line 3091, in resolve
>     self._resolve_invocations(solution)
>   File "/nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/.resholve-wrapped", line 3050, in _resolve_invocations
>     source.look_for_external_sub_execution(self.name, invocation)
>   File "/nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/.resholve-wrapped", line 4046, in look_for_external_sub_execution
>     if handler(parsed, invocation):
>   File "/nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/.resholve-wrapped", line 3717, in handle_external_sed
>     if self._find_sed_e_cmd(first):
>   File "/nix/store/amyyid3bkdk3nfw02nxcl6xw9lgbfjdr-resholve-0.9.1/bin/.resholve-wrapped", line 3659, in _find_sed_e_cmd
>     close_fds=True,
>   File "/nix/store/gqgkqp9sfjkz61mv96dp8k6ll3acinq6-python-2.7.18.7/lib/python2.7/subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "/nix/store/gqgkqp9sfjkz61mv96dp8k6ll3acinq6-python-2.7.18.7/lib/python2.7/subprocess.py", line 1046, in _execute_child
>     child_exception = pickle.loads(data)
>   File "/nix/store/gqgkqp9sfjkz61mv96dp8k6ll3acinq6-python-2.7.18.7/lib/python2.7/pickle.py", line 1388, in loads
>     return Unpickler(file).load()
>   File "/nix/store/gqgkqp9sfjkz61mv96dp8k6ll3acinq6-python-2.7.18.7/lib/python2.7/pickle.py", line 864, in load
>     dispatch[key](self)
>   File "/nix/store/gqgkqp9sfjkz61mv96dp8k6ll3acinq6-python-2.7.18.7/lib/python2.7/pickle.py", line 977, in load_string
>     self.append(rep.decode("string-escape"))
>   File "/nix/store/gqgkqp9sfjkz61mv96dp8k6ll3acinq6-python-2.7.18.7/lib/python2.7/encodings/__init__.py", line 100, in search_function
>     level=0)
> TypeError: _oildev_import() got an unexpected keyword argument 'fromlist'
> ```
> </details>
> 
> _Originally posted by @lopsided98 in https://github.com/NixOS/nixpkgs/issues/288465#issuecomment-1975558948_
>

**Comment by lopsided98** [comment]
It looks like there is a finite set of programs that resholve tries to run (just awk and sed?). It seems like paths to these programs for the build platform can be hardcoded at build time.

**Comment by abathur** [comment]
This should be working in nixpkgs master/unstable now.
