### ISSUE TITLE
variables run as commands (first word)

### ISSUE THREAD

**Issue by abathur** [abathur/resholve#3]
I'm not sure how resholved should handle variables used as a command (i.e., the first word of a statement). I'm already aware of a number of patterns here and have found real-world examples in common programs where not handling these is "wrong", but I could use some feedback on how to handle it (and perhaps how often people run into it).

A few such patterns include:
- Storing a frequently-used command in a variable name to make it easier to change or override and replacing uses of the command with the variable.
- When a script has to do a little work to figure out what the right command is (i.e., it changes depending on user config, command-line options, platform, software versions, sanity checks of command behavior/options/output).
- Running positional parameters as commands. This is done for multiple distinct reasons, like wrapping an execution with other logic, exposing script functions for external execution, etc. (I think most of these will be okay-ish, so they're currently exempted from the warning. For them to be *robustly* okay, resholved would probably have to figure out how and where they're being invoked, and then try to resolve the appropriate positional arg of each invocation.)

This pattern, at least with named variables, will now print a warning/request for feedback, such as:

```
  $GIT_PROGRAM status
  ^~~~~~~~~~~~
[ stdinNone ]:7: FEEDBACK WANTED: Letting dynamic command (first-word variable) through for now. Not sure if this is 'right' or not. ...
```

As the fact that resholved issues a warning here suggests, it isn't terribly hard to spot this behavior. Fixing it is less straightforward. Continuing the `$GIT_PROGRAM` example, resholved would either need to replace instances of the variable with a resolved program, or it needs to figure out where the variable is set and resolve whatever it's set to (but only if it's not something like a builtin/function/alias?)

Trying to do this automatically probably entails a jump in complexity and greater risk of breaking a resolved script in some way.

It is easy to throw an error here and just make/let the user override it, though I'm not sure how the override API should approach it...
- It could enable the user to specify a replacement for the variable, but it seems tricky to do this robustly (do we just replace instances used as a command? also instances used inline? does the script build up the variable iteratively in multiple steps to add flags and options?)
- The API could specify a target variable, and a string/identifier to try and resolve wherever it's defined. This might be a little more robust against the script iteratively constructing the command, but I can imagine it breaking down in other ways (the script uses the variable for flow control, or performs string operations like substitution or positional indexing/slicing).

**Comment by abathur** [comment]
I've made up my mind that this "should" be an error (because I've found a scenario where I personally missed identifying a dependency that I would have caught if this step had been an error that I had to fix instead of a warning.)

I'm not quite sure what the fix is yet... 
- This is a fairly common warning, so if it's not a silly amount of work, it would be nice to directly solve any straightforward cases.
- If there's a reliable heuristic for splitting simple variables that are *only* set and read (I am doubtful), it could be productive to let the user specify imperative replacements/overwrites for this set of variables and save harder triage for steps for variables getting used in more complex ways.

**Comment by grahamc** [comment]
Just wanted to add an example of when I saw it, and what I'm trying to do:

```
  newversion="$($newsyspath/sw/bin/nixos-version)"
                ^~~~~~~~~~~
[ stdinNone ]:26: FEEDBACK WANTED: Letting dynamic command (first-word variable) through for now. Not sure if this is 'right' or not. Weigh in @ https://github.com/abathur/resholved/issues/3
```


Here is my script:

```
#!/bin/sh

newsyspath=$(readlink -f "/var/cache/upgrade/staged")
prevsyspath=$(readlink -f /nix/var/nix/profiles/system)

if [ ! -e "$newsyspath" ]; then
	echo "No new system."
	exit 0
fi

if [ "$newsyspath" = "$prevsyspath" ]; then
	echo "System remains unchanged."
	exit 0
fi

prevversion="$(/run/current-system/sw/bin/nixos-version)"
newversion="$($newsyspath/sw/bin/nixos-version)"

echo "Upgrade from $prevversion to $newversion?"
```

**Comment by abathur** [comment]
Ooof. Thanks for adding this.

**Comment by abathur** [comment]
This is partially closed by the `--keep $varname` directive. I say partially because I think a more principled solution may be available eventually, but it'll entail paying more attention to variables than resholve currently does (and, by proxy, to all of the variable-setting commands, etc.)
