### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'script'

### ISSUE THREAD

**Issue by cole-h** [abathur/resholve#71]
https://gist.github.com/cole-h/424a8265ce97cdc68ed264efbb39e14d

**Comment by abathur** [comment]
Blocker? I've copied the sed command into my parser test-cases and confirmed it fails there as well. I'm shaving a yak at the moment, but it's not an essential one so I can triage if needed.

Aside: IDK how much overhead gisting the repros is for you, but if it's annoying: I added a sub-command syntax test recently that might help at least in these terse sub-command syntax cases? 

I pushed up 6adf3d3 to show how I'm adding this test. If it smells like a process improvement I suspect it'd be fine to just add one, push it up on a branch, and link it in the issue? (I imagine writing a real commit message and opening a PR would squander any time saved)

**Comment by cole-h** [comment]
Not a blocker -- easily worked around by writing to a temporary file and then moving the temp file over the desired destination.

Gisting the stuff isn't hard -- coming up with minimal reproductions are measurably more-so :P

Also note that the example doesn't fail if you run it on e.g. `/mnt` -- it's only `/mnt/etc` (from what I remember) and descendants that trigger this.
