### ISSUE TITLE
Question - what's the proper way to ignore an executable

### ISSUE THREAD

**Issue by peterhoeg** [abathur/resholve#83]
Let's say you have a 3rd party script that tries to be support multiple different binaries (vlc and mpv as an example) and uses `command -v mpv` to check for it on the path.

We probably just want to pick one and ignore the other.

What is the proper way to handle that?

**Comment by abathur** [comment]
If I am understanding right, you want to fake externals for them.

**Comment by abathur** [comment]
I have lightly considered whether it's worth having an obvious/meaningful idiom for these. 

But I am also hesitant to make an Nth way of doing the same thing  in case it just confuses (and might oversell how smart resholve can be about alts?)

**Comment by peterhoeg** [comment]
I was going about it in the wrong way. Apologies for the noise.

**Comment by abathur** [comment]
No worries. It's helpful to accumulate different goal descriptions and document how they map to the directive toolkit.

**Comment by LunNova** [comment]
Is there an inline equivalent? I'm writing some scripts intended for use with resholve and would like to specify inline when they're intended to be picked up from the path, if that's possible.

**Comment by abathur** [comment]
No. The AST it uses doesn't expose comments (or at least, I haven't stumbled on the lever in the oil code base that would make it). 

I did have it on my radar early on, but without them in the AST it'd need to lean on an additional parser, manage whatever quirks/dependencies it comes with, and take the performance hit for parsing twice, and need some potentially complex way to map between the ASTs (the oil AST has an idiomatic position system that is sequential through the document and not, say, line/col). 

This is why resholve uses a tail comment block, too.

Is this just about simplifying invocations, or do you have a case where the existing directives just can't behave like you need?

**Comment by LunNova** [comment]
Mostly to simplify/make things more explicit. Would make invoking something on the path stand out in the script instead of depending on resholv having fake set in another file.

**Comment by abathur** [comment]
Gotcha. Fair. Explicit is good... 

You could probably add a tail comment block in resholve's format with the corresponding resholve directive, but I suspect that's too far from the invocations to be satisfying (and it would need maintenance if the resholve schema changes).

I guess we could sanction a descriptively-named ~magic non-existing command that resholve special-cases, but documenting it would muddy the message that resholve doesn't entail injecting cruft into scripts that renders them unusable in other environments...

I suppose you could do a cheap version of the same with a descriptive internal function that just runs "$@"?
