### ISSUE TITLE
when invoked with multiple scripts, `--prologue` only applies to the first

### ISSUE THREAD

**Issue by uninsane** [abathur/resholve#89]
i'm invoking resholve from nix with something like this:
```nix
resholve.mkDerivation {
  # ...
  solutions = {
    default = {
      scripts = [ "bin/first" "bin/second" ];
      prologue = "bin/my_prologue";
    };
  };
}
```

where `bin/my_prologue` contains "echo prologue".

the output is
- `bin/first` (correct):
```sh
#!/nix/store/nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16/bin/bash
# begin prologue inserted by resholve
echo prologue

# end prologue inserted by resholve
...
```
- `bin/second` (incorrect):
```sh
#!/nix/store/nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16/bin/bash
# begin prologue inserted by resholve

# end prologue inserted by resholve
```

i would expect the prologue to be inserted into all scripts. instead, only the first script gets the full prologue and the other scripts get some empty skeleton.

## probable cause

the code that handles prologues looks like this:
```py
        # if the user has specified a prepend string, find the first
        # actual code span, so that we can inject before it.
        if full and self.prologue:
            first_span = find_earliest_spid(self.root)
            cursor.PrintUntil(first_span)
            to.write("\n# begin prologue inserted by resholve\n")
            to.write(self.prologue.read())
            to.write("\n# end prologue inserted by resholve\n")
            cursor.PrintUntil(first_span)
```

if this gets run on each file without resetting the cursor for `self.prologue`, that would match the observed behavior. i'd try adding a `self.prologue.seek(0, pos="abs")` in there, but unfortunately i don't have the time to setup a dev environment at the moment :-(

**Comment by abathur** [comment]
@uninsane This fix is now available in `nixpkgs-unstable` and should be available in `nixos-unstable` soonish.
