### ISSUE TITLE
Missing subsequent `! type <command>` replacements

### ISSUE THREAD

**Issue by adamcstephens** [abathur/resholve#94]
Hello, I'm trying to resholve this script: https://github.com/intel/S0ixSelftestTool/blob/1b6db3c3470a3a74b052cb728a544199661d18ec/s0ix-selftest-tool.sh

Using this package: https://github.com/adamcstephens/dotfiles/blob/9d117abedfffb098ca334a69deba9c48c85b3fc4/nix/packages/s0ix-selftest-tool/default.nix

Resholve is correctly detecting and replacing one instance of `! type powertop` but fails on subsequent replacements. See:

```
─❯ rg "type.*powertop" result/bin/s0ix-selftest-tool
737:  if ! type /nix/store/1yl0sczx0z6i9l3bwf5bjnax40p07pxp-powertop-2.15/bin/powertop 1>/dev/null 2>&1; then
943:  if ! type powertop 1>/dev/null 2>&1; then
1341:  if ! type powertop 1>/dev/null 2>&1; then
1379:  if ! type powertop 1>/dev/null 2>&1; then
```

I am not sure if I understand how to `fix` this manually, but I suspected this is a bug I should report anyway.

**Comment by abathur** [comment]
Agree this looks like a bug. I'll try to take a look tonight.

Don't think any of resholve's ~levers will be able to compensate by themselves. If you're blocked and need it to work, I'd recommend using substituteInPlace to patch `type powertop` -> `type ${powertop}/bin/powertop` and then using a `keep` directive to tell resholve that the absolute path is fine:

```
keep."${powertop}/bin/powertop" = true;
```

**Comment by abathur** [comment]
Fix should be available in nixpkgs after nixos/nixpkgs#211191

**Comment by adamcstephens** [comment]
Thanks for the quick fix!

**Comment by abathur** [comment]
Should be available in unstable now.
